#!/bin/bash
set -euo pipefail

echo "Generating random passwords and secret keys for Superset..."

# Generate random strings for secrets
# SECRET_KEY and GUEST_TOKEN_JWT_SECRET are recommended to be base64-encoded and long (e.g., 42 chars)
SUPERSET_SECRET_KEY=$(openssl rand -base64 42)
GUEST_TOKEN_JWT_SECRET=$(openssl rand -base64 42)

# Database and Redis passwords (alphanumeric with underscore, 20 chars long)
DB_PASSWORD=$(head /dev/urandom | tr -dc A-Za-z0-9_ | head -c 20)
REDIS_PASSWORD=$(head /dev/urandom | tr -dc A-Za-z0-9_ | head -c 20)

# Pgadmin password (alphanumeric with underscore, 16 chars long)
PGADMIN_DEFAULT_PASSWORD=$(head /dev/urandom | tr -dc A-Za-z0-9_ | head -c 16)

# Superset Admin password (alphanumeric with underscore, 16 chars long)
ADMIN_PASSWORD=$(head /dev/urandom | tr -dc A-Za-z0-9_ | head -c 16)

# Websocket JWT Secret (if websockets are enabled)
WEBSOCKET_JWT_SECRET=$(openssl rand -base64 32)

# Create a temporary YAML file with the generated secrets
FILE_PREFIX=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 13; echo)
# FILE_DATE=$(date '+%d_%m_%Y__%H_%M')
# SECRETS_FILE_NAME="${FILE_PREFIX}--${FILE_DATE}-superset-deployment-secrets.yaml"
SECRETS_FILE_NAME="${FILE_PREFIX}-superset-deployment-secrets.yaml"


cat <<EOF > "$SECRETS_FILE_NAME"
---
# This file is auto-generated by generate-variables.sh and contains sensitive information
apiVersion: v1
kind: Secret
metadata:
  name: superset-deployment-secrets
type: Opaque
stringData:
  SUPERSET_DB_USER: 'superset'
  SUPERSET_DB_NAME: 'superset'
  SUPERSET_DB_PASSWORD: '$DB_PASSWORD'
  POSTGRES_PASSWORD: '$DB_PASSWORD'
  SUPERSET_SECRET_KEY: '$SUPERSET_SECRET_KEY'
  SUPERSET_ADMIN_PASSWORD: '$ADMIN_PASSWORD'
  REDIS_PASSWORD: '$REDIS_PASSWORD'
  WEBSOCKET_JWT_SECRET: '$WEBSOCKET_JWT_SECRET'
  GUEST_TOKEN_JWT_SECRET: '$GUEST_TOKEN_JWT_SECRET'
  POSTGREST_DB_URI: 'postgres://authenticator:$DB_PASSWORD@superset-postgresql:5432/superset'
  POSTGREST_API_URL: 'https://db.dashverse.cloud'
  POSTGREST_SERVER_CORS_ALLOWED_ORIGINS: 'https://apidocs.dashverse.cloud,https://api.dashverse.cloud,https://db.dashverse.cloud'
  PGADMIN_DEFAULT_EMAIL: 'admin@example.com'
  PGADMIN_DEFAULT_PASSWORD: '$PGADMIN_DEFAULT_PASSWORD'
EOF
echo "Generated secrets file: $SECRETS_FILE_NAME"


cat <<EOF > secrets.env
# This file is auto-generated by generate-variables.sh and contains sensitive information
export SUPERSET_DB_USER='superset'
export SUPERSET_DB_NAME='superset'
export SUPERSET_DB_PASSWORD='$DB_PASSWORD'
export POSTGRES_PASSWORD='$DB_PASSWORD'
export SUPERSET_SECRET_KEY='$SUPERSET_SECRET_KEY'
export SUPERSET_ADMIN_PASSWORD='$ADMIN_PASSWORD'
export REDIS_PASSWORD='$REDIS_PASSWORD'
export WEBSOCKET_JWT_SECRET='$WEBSOCKET_JWT_SECRET'
export GUEST_TOKEN_JWT_SECRET='$GUEST_TOKEN_JWT_SECRET'
export POSTGREST_DB_URI='postgres://authenticator:$DB_PASSWORD@superset-postgresql:5432/superset'
export POSTGREST_API_URL='https://db.dashverse.cloud'
export POSTGREST_SERVER_CORS_ALLOWED_ORIGINS='https://apidocs.dashverse.cloud,https://api.dashverse.cloud,https://db.dashverse.cloud'
export PGADMIN_DEFAULT_EMAIL='admin@example.com'
export PGADMIN_DEFAULT_PASSWORD='$PGADMIN_DEFAULT_PASSWORD'
EOF
echo "Generated secrets file: secrets.env"


DB_CONFIG_FILE_NAME="../DBModel/db_config.json"
cat <<EOF > "$DB_CONFIG_FILE_NAME"
{
    "dbname": "superset",
    "user": "postgres",
    "password": "$DB_PASSWORD",
    "host": "superset-postgresql",
    "port": 5432
}
EOF
echo "Generated db config file: $DB_CONFIG_FILE_NAME"


# source ./secrets.env
# envsubst < deployment.yaml | less
# envsubst < deployment.yaml | kubectl apply -f

