version: "3.9"

services:
  db:
    image: postgres:17.2
    restart: always
    hostname: postgres
    # set shared memory limit when using docker-compose
    shm_size: 512mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  pgadmin:
    image: dpage/pgadmin4:8.14.0
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@everse.software
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
      - PGPASSFILE=/pgpass
    entrypoint: /bin/sh -c "chmod 600 /pgpass; /entrypoint.sh;"
    user: root
    configs:
      - source: pgadmin_servers.json
        target: /pgadmin4/servers.json
      - source: pgpass
        target: /pgpass
    depends_on:
      - "db"

configs:
  pgpass:
    content: db:5432:*:postgres:postgres
  pgadmin_servers.json:
    content: |
      {"Servers": {
          "1": {
            "Group": "Servers",
            "Name": "Superset Postgres Server",
            "Host": "0.0.0.0",
            "Port": 5432,
            "MaintenanceDB": "superset",
            "Username": "superset",
            "PassFile": "/pgpass",
            "SSLMode": "prefer"
          },
          "2": {
            "Group": "Servers",
            "Name": "Local Postgres Server",
            "Host": "db",
            "Port": 5432,
            "MaintenanceDB": "postgres",
            "Username": "postgres",
            "PassFile": "/pgpass",
            "SSLMode": "prefer"
          },
        }
      }
