version: "3.9"

services:
  db:
    image: postgres:17.2
    restart: always
    hostname: postgres
    # set shared memory limit when using docker-compose
    shm_size: 512mb
    ports:
      - "5431:5431"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGPORT: 5431
    network_mode: "host"

  pgadmin:
    image: dpage/pgadmin4:9.0.0
    ports:
      - 5050:5050
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@everse.software
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
      - PGADMIN_LISTEN_PORT=5050
      - PGPASSFILE=/pgpass
    entrypoint: /bin/sh -c "chmod 600 /pgpass; /entrypoint.sh;"
    user: root
    configs:
      - source: pgadmin_servers.json
        target: /pgadmin4/servers.json
      - source: pgpass
        target: /pgpass
    depends_on:
      - "db"
    # extra_hosts:
    # - "host.docker.internal:host-gateway"
    # - "host.docker.internal:172.17.0.1"
    network_mode: "host"

configs:
  pgpass:
    # content: db:5431:*:postgres:postgres
    content: |
      0.0.0.0:5431:*:postgres:postgres
      0.0.0.0:5432:*:superset:superset
  pgadmin_servers.json:
    content: |
      {"Servers": {
          "1": {
            "Group": "Servers",
            "Name": "Docker Postgres Server",
            "Host": "0.0.0.0",
            "Port": 5431,
            "MaintenanceDB": "postgres",
            "Username": "postgres",
            "PassFile": "/pgpass",
            "SSLMode": "prefer"
          },
          "2": {
            "Group": "Servers",
            "Name": "Superset Postgres Server",
            "Host": "0.0.0.0",
            "Port": 5432,
            "MaintenanceDB": "superset",
            "Username": "superset",
            "PassFile": "/pgpass",
            "SSLMode": "prefer"
          }
        }
      }
