slice_name: Average Quality Score
description: Average pass rate across all software and dimensions in the dataset.
  Track this as the headline outcome metric of training effectiveness.
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  metric:
    label: pass_rate
    expressionType: SIMPLE
    column:
      column_name: pass_rate
    aggregate: AVG
  header_font_size: 0.4
  subheader_font_size: 0.15
  subheader: Average Pass Rate
query_context: null
cache_timeout: null
uuid: 9940ea96-c99d-4f4c-8854-2c83d30df63d
version: 1.0.0
dataset_uuid: c57303cb-cad4-42f6-9f01-6c7438a03ce3
