slice_name: Checks by Status
description: Share of checks that passed, failed, or were not applicable. A large
  fail slice signals systematic issues; a small fail slice means the project is healthy.
certified_by: null
certification_details: null
viz_type: pie
params:
  groupby:
  - status
  metric:
    label: occurrences
    expressionType: SIMPLE
    column:
      column_name: occurrences
    aggregate: SUM
  color_scheme: supersetColors
  show_labels: true
  show_legend: true
query_context: null
cache_timeout: null
uuid: 2e989805-a542-490d-ba7d-35ebd34db576
version: 1.0.0
dataset_uuid: 596fa4e1-48bb-44c3-b664-f0586e1c7b0e
