slice_name: Common Issues Bar
description: Top 15 indicators with the highest failure counts across all assessed
  software. Tackle the largest bars first for the highest-impact fixes.
certified_by: null
certification_details: null
viz_type: dist_bar
params:
  groupby:
  - indicator_name
  metrics:
  - label: failure_count
    expressionType: SIMPLE
    column:
      column_name: failure_count
    aggregate: SUM
  color_scheme: supersetColors
  row_limit: 15
  show_bar_value: true
query_context: null
cache_timeout: null
uuid: 3df8ccd7-afe1-4365-8e27-d846ed34c8a7
version: 1.0.0
dataset_uuid: 4bcfa543-1597-476f-a4a9-ea7dc1c437d2
