slice_name: My Quality Profile
description: Distribution of passed checks across quality dimensions. Large slices
  identify your strengths; small slices show neglected dimensions worth investing
  in.
certified_by: null
certification_details: null
viz_type: pie
params:
  groupby:
  - dimension_name
  metric:
    label: passed
    expressionType: SIMPLE
    column:
      column_name: passed
    aggregate: SUM
  color_scheme: supersetColors
  show_labels: true
  show_legend: true
query_context: null
cache_timeout: null
uuid: 1fc6d93f-76db-4c47-bd5f-c8536bd7574a
version: 1.0.0
dataset_uuid: c57303cb-cad4-42f6-9f01-6c7438a03ce3
