slice_name: Pass Rate KPI
description: Overall percentage of checks that passed across all assessments. Aim
  for 80% or higher as a healthy target across the portfolio.
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  metric:
    label: pass_rate
    expressionType: SIMPLE
    column:
      column_name: pass_rate
    aggregate: AVG
  header_font_size: 0.4
  subheader_font_size: 0.15
  subheader: Average Pass Rate %
query_context: null
cache_timeout: null
uuid: 8e99c80d-7f72-4715-b6f6-6bb02841a44e
version: 1.0.0
dataset_uuid: c57303cb-cad4-42f6-9f01-6c7438a03ce3
