slice_name: Project Health
description: Average pass rate across your portfolio. Use as an at-a-glance health
  indicator at PI status meetings.
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  metric:
    label: pass_rate
    expressionType: SIMPLE
    column:
      column_name: pass_rate
    aggregate: AVG
  header_font_size: 0.4
  subheader_font_size: 0.15
  subheader: Portfolio Health %
query_context: null
cache_timeout: null
uuid: c678515d-d10a-4840-af64-ee42c8f68b0e
version: 1.0.0
dataset_uuid: c57303cb-cad4-42f6-9f01-6c7438a03ce3
