slice_name: Quality by Software
description: Total number of checks performed per software project. Wide bars indicate
  well-tested projects; short bars suggest assessments were skipped or limited.
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  x_axis: software_name
  metrics:
  - label: count
    expressionType: SQL
    sqlExpression: COUNT(*)
  color_scheme: supersetColors
  row_limit: 20
  show_legend: false
query_context: null
cache_timeout: null
uuid: ded346e3-839c-4e96-b2a2-da41930ce56e
version: 1.0.0
dataset_uuid: 53b08a54-2e42-4412-b4dd-a4f8be57dfab
