slice_name: Training Effectiveness
description: Trend of assessment volume over time, expected to rise after a training
  intervention. Investigate flat or falling lines as feedback for course design.
certified_by: null
certification_details: null
viz_type: echarts_timeseries_line
params:
  x_axis: month
  metrics:
  - label: assessments
    expressionType: SIMPLE
    column:
      column_name: assessments
    aggregate: SUM
  color_scheme: supersetColors
  show_legend: true
  y_axis_format: .0f
query_context: null
cache_timeout: null
uuid: 49f0c2eb-7b5b-4631-bd81-d67c319d5ffb
version: 1.0.0
dataset_uuid: 80662b12-f989-4498-be68-1afe226d00a2
