slice_name: Total Assessments
description: Total quality assessments submitted across all software. Compare against
  Total Software Projects to gauge how often each project is being reassessed.
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  metric:
    label: count
    expressionType: SQL
    sqlExpression: COUNT(*)
  header_font_size: 0.4
  subheader_font_size: 0.15
  subheader: Assessments Completed
query_context: null
cache_timeout: null
uuid: 04a5f0a9-87de-4262-a4c9-19eb93052c5a
version: 1.0.0
dataset_uuid: 2e5838cf-b850-4a74-997c-a709e7c36808
